{{ .base | strings.TrimSpace }}

RUN apk add --no-cache \
	ca-certificates \
	curl \
	git \
	libcap

ENV XCADDY_VERSION=v{{ .xcaddy_config.version }}
# Configures xcaddy to build with this version of Caddy
ENV CADDY_VERSION=v{{ .config.caddy_version }}
# Configures xcaddy to not clean up post-build (unnecessary in a container)
ENV XCADDY_SKIP_CLEANUP=1
# Sets capabilities for output caddy binary to be able to bind to privileged ports
ENV XCADDY_SETCAP=1

RUN set -eux; \
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		x86_64)  binArch='amd64'; checksum='{{ .xcaddy_checksums.amd64 }}' ;; \
		armhf)   binArch='armv6'; checksum='{{ .xcaddy_checksums.arm32v6 }}' ;; \
		armv7)   binArch='armv7'; checksum='{{ .xcaddy_checksums.arm32v7 }}' ;; \
		aarch64) binArch='arm64'; checksum='{{ .xcaddy_checksums.arm64v8 }}' ;; \
		ppc64el|ppc64le) binArch='ppc64le'; checksum='{{ .xcaddy_checksums.ppc64le }}' ;; \
		riscv64) binArch='riscv64'; checksum='{{ .xcaddy_checksums.riscv64 }}' ;; \
		s390x)   binArch='s390x'; checksum='{{ .xcaddy_checksums.s390x }}' ;; \
		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
	esac; \
	wget -O /tmp/xcaddy.tar.gz "https://github.com/caddyserver/xcaddy/releases/download/v{{ .xcaddy_config.version }}/xcaddy_{{ .xcaddy_config.version }}_linux_${binArch}.tar.gz"; \
	echo "$checksum  /tmp/xcaddy.tar.gz" | sha512sum -c; \
	tar x -z -f /tmp/xcaddy.tar.gz -C /usr/bin xcaddy; \
	rm -f /tmp/xcaddy.tar.gz; \
	chmod +x /usr/bin/xcaddy;

COPY caddy-builder.sh /usr/bin/caddy-builder

WORKDIR /usr/bin
