#!/bin/bash
set -exo pipefail

# install bashbrew for the build
docker create --name bb hairyhenderson/bashbrew
docker cp bb:/bin/bashbrew .

export BASHBREW_LIBRARY=./library
export BASHBREW_NAMESPACE=caddy

./bashbrew build caddy
./bashbrew push --dry-run caddy
