#!/bin/bash
set -exuo pipefail

export DOCKER_REPO=${DOCKER_REPO:-caddy/caddy}
export DOCKER_TAG=${DOCKER_TAG:-latest}
export IMAGE_NAME=${IMAGE_NAME:-$DOCKER_REPO:$DOCKER_TAG}

docker push "$DOCKER_REPO:alpine"
docker push "$DOCKER_REPO:scratch"

# This magic figures out if we're currently on a tag (i.e. a release).
# We only want to have special tags for releases.
if (git describe --abbrev=0 --exact-match &>/dev/null); then
  tag=$(git describe --abbrev=0 --exact-match)
  # splits the major/minor versions from $tag - assumes it's a 3-part semver
  major=${tag%%\.*}
  minor=${tag%\.*}

  # make sure latest is tagged when it's a versioned build too
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:latest"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:$tag"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:$major"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:$minor"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:${tag}-scratch"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:${major}-scratch"
  docker tag "$DOCKER_REPO:scratch" "$DOCKER_REPO:${minor}-scratch"
  docker tag "$DOCKER_REPO:alpine" "$DOCKER_REPO:${tag}-alpine"
  docker tag "$DOCKER_REPO:alpine" "$DOCKER_REPO:${major}-alpine"
  docker tag "$DOCKER_REPO:alpine" "$DOCKER_REPO:${minor}-alpine"

  docker push "$DOCKER_REPO:latest"
  docker push "$DOCKER_REPO:$tag"
  docker push "$DOCKER_REPO:$major"
  docker push "$DOCKER_REPO:$minor"
  docker push "$DOCKER_REPO:${tag}-scratch"
  docker push "$DOCKER_REPO:${major}-scratch"
  docker push "$DOCKER_REPO:${minor}-scratch"
  docker push "$DOCKER_REPO:${tag}-alpine"
  docker push "$DOCKER_REPO:${major}-alpine"
  docker push "$DOCKER_REPO:${minor}-alpine"
fi
