FROM b AS builder

RUN caddy-builder \
    github.com/caddyserver/nginx-adapter \
    github.com/hairyhenderson/caddy-teapot-module@v0.0.3-0

FROM caddy/caddy

COPY --from=builder /caddy.exe /caddy.exe
