FROM golang:1.14.0-alpine3.11 as builder

WORKDIR /src

RUN apk add --no-cache \
    git \
    ca-certificates

ENV CADDY_SOURCE_VERSION={{ .config.caddy_version }}

RUN git clone -b $CADDY_SOURCE_VERSION https://github.com/caddyserver/caddy.git --single-branch

WORKDIR /src/caddy/cmd/caddy

COPY caddy-builder.sh /usr/bin/caddy-builder
